# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.
name: R-CMD-check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse:latest # Image that already has R and tidyverse installed

    steps:
      - uses: actions/checkout@v4 # Check out the repository (latest version)

      - name: Install additional R packages
        run: |
          install.packages("rcmdcheck") # Install the r command check package
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Run R CMD check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
